name: Build and Test .NET App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd dotnet-app
          dotnet restore

      - name: Build project
        run: |
          cd dotnet-app
          dotnet build --no-restore --configuration Release

      - name: Run tests
        run: |
          cd dotnet-app
          dotnet test --no-build --verbosity normal

      - name: Check code formatting
        run: |
          cd dotnet-app
          dotnet format --verify-no-changes

      - name: Check NuGet vulnerabilities
        run: |
          cd dotnet-app
          dotnet list package --vulnerable
