name: Final-pip

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
name: Checkout repository
      uses: actions/checkout@v2,

      
name:  Login f Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }},

      
name:  Build w Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mohamedchliyah01/dotnet-app:latest, mohamedchliyah01/dotnet-app:${{ github.run_number }},

      
name:  Format Check
      run: dotnet format --verify-no-changes, || true

      
name:  Scan NuGet Vulnerabilities
      run: dotnet list package --vulnerable, || true 

      
name: 🔔 Envoyer Notification Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \-X POST \-d "{"content": "CI Success: Build #${{ github.run_number }} Daz mezyan!"}" \https://discord.com/api/webhooks/1374541317203300492/eBq-330IkJ1_ZJZRiidtB5LUXIoLVrUHbPweFFDACCommoQRIsdBCJytRIXyz5TeRQBp,

      
name: ❌ Envoyer Notification Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \-X POST \-d "{"content": "CI Failed: Build #${{ github.run_number }} Ma dazch mezyan!"}" \https://discord.com/api/webhooks/1374541317203300492/eBq-330IkJ1_ZJZRiidtB5LUXIoLVrUHbPweFFDACCommoQRIsdBCJytRIXyz5TeRQBp,
